global:
  imagePullPolicy: Always
  images:
    confserver: curiefense/confserver
    curielogger: curiefense/curielogger
    curietasker: curiefense/curietasker
    logdb: curiefense/logdb
    redis: curiefense/redis
    curielogserver: curiefense/curielogserver
    uiserver: curiefense/uiserver
    curiesync: curiefense/curiesync
    grafana: curiefense/grafana
    prometheus: curiefense/prometheus
    fluentd: curiefense/fluentd

  storage:
    # use the default storage class if null
    storage_class_name: null
    confserver_storage_size: '1Gi'
    grafana_storage_size: '1Gi'
    logdb_storage_size: '10Gi'
    elasticsearch_storage_size: '10Gi'
    prometheus_storage_size: '1Gi'
    redis_storage_size: '1Gi'

  settings:
    curieconf_manifest_url: 's3://curiefense-test01/prod/manifest.json'
    # supported types: 'postgres', 'elasticsearch'
    curiefense_logdb_type: 'elasticsearch'
    # supported types: 'fluentd', 'logstash'
    curiefense_es_forwarder: 'logstash'
    # change curiefense_es_hosts if you supply your own elasticsearch server. Using several servers is not (yet?) fully supported by this chart
    curiefense_es_hosts: 'http://elasticsearch:9200/'
    # change curiefense_logstash_url if you supply your own logstash server.
    curiefense_logstash_url: 'http://logstash:5001/'
    # change curiefense_fluentd_url if you supply your own fluentd server.
    curiefense_fluentd_url: 'http://fluentd:5001/'
    # change curiefense_kibana_url if you supply your own kibana server.
    curiefense_kibana_url: 'http://kibana:5601/'
    # change curiefense_db_hostname if you supply your own postgres server
    curiefense_db_hostname: 'logdb'
    # supported types: 's3', 'gs'
    curiefense_bucket_type: 's3'
    curiefense_es_index_name: 'curieaccesslog'
    # docker_tag will be overridden by deploy.sh
    docker_tag: 'latest'

  requests:
    cpu:
      curielogger: "100m"
      redis: "10m"
      logstash: "100m"
      kibana: "100m"
      logdb: "1"
      uiserver: "100m"
      confserver_init: "100m"
      confserver_nginx: "10m"
      confserver_uwsgi: "100m"
      curietasker: "100m"
      prometheus: "100m"
      grafana: "20m"
      curielogserver_nginx: "10m"
      curielogserver_uwsgi: "10m"
      elasticsearch: "1"

  enable:
    # set to false to disable parts of this deployment, ex. if you prefer to use your own versions
    grafana: true
    prometheus: true
    # postgres database to store logs. Can be replaced with AWS Aurora
    logdb: true
    kibana: true
    elasticsearch: true
    fluentd: true
    logstash: true
