{{- $curielogger := default .Values.global.curielogger (fromYaml "{}") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: curielogger
    app.kubernetes.io/part-of: "curiefense"
  name: curielogger
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: curielogger
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: curielogger
        app.kubernetes.io/part-of: "curiefense"
    spec:
      containers:
{{- if eq .Values.global.settings.curiefense_es_forwarder "filebeat" }}
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.10.1
        args:
          - "-v"
          - "-e"
        env:
        - name: ELASTICSEARCH_URL
          value: "{{ .Values.global.settings.curiefense_es_hosts }}"
        - name: KIBANA_URL
          value: "{{ .Values.global.settings.curiefense_kibana_url }}"
        - name: INDEX_NAME
          value: {{ .Values.global.settings.curiefense_es_index_name }}
        volumeMounts:
          - name: curielogger
            mountPath: /var/log/curielogger
          - name: filebeat-configmap
            subPath: filebeat.yml
            mountPath: /usr/share/filebeat/filebeat.yml
          - name: filebeat-configmap
            subPath: ilm.json
            mountPath: /usr/share/filebeat/ilm.json
          - name: filebeat-configmap
            subPath: template.json
            mountPath: /usr/share/filebeat/template.json
{{- end }}
      - name: curielogger
        env:
{{- if $curielogger.extraEnv }}
{{ $curielogger.extraEnv | toYaml | indent 8 }}
{{- end }}
        - name: CURIELOGGER_METRICS_PROMETHEUS_ENABLED
          value: "{{ .Values.global.settings.curiefense_metrics_prometheus_enabled }}"
        - name: ELASTICSEARCH_URL
          value: "{{ .Values.global.settings.curiefense_es_hosts }}"
{{- if eq .Values.global.settings.curiefense_es_forwarder "logstash" }}
        - name: CURIELOGGER_OUTPUTS_LOGSTASH_ENABLED
          value: "true"
        - name: CURIELOGGER_OUTPUTS_LOGSTASH_URL
          value: "{{ .Values.global.settings.curiefense_logstash_url }}"
        - name: USE_DATA_STREAMS
          value: "false"
{{- end }}
{{- if eq .Values.global.settings.curiefense_es_forwarder "fluentd" }}
        - name: CURIELOGGER_USES_FLUENTD
          value: "true"
        - name: CURIELOGGER_FLUENTD_URL
          value: "{{ .Values.global.settings.curiefense_fluentd_url }}"
{{- end }}
        - name: CURIELOGGER_KIBANA_URL
          value: "{{ .Values.global.settings.curiefense_kibana_url }}"
{{- if .Values.global.enable.kibana }}
        - name: CURIELOGGER_INITIALIZE_KIBANA_INDEX
          value: "true"
{{- end }}
        {{ if regexMatch ".*/.*:" .Values.global.images.curielogger }}
        {{/* The image name contains a version tag (e.g. for tests), do not append docker_tag */}}
        image: {{ .Values.global.images.curielogger }}
        {{ else }}
        image: {{ .Values.global.images.curielogger }}:{{ .Values.global.settings.docker_tag }}
        {{ end }}
{{- if eq .Values.global.settings.curiefense_es_forwarder "filebeat" }}
        args:
          - /bin/curielogger |rotatelogs -e -n 20 /var/log/curielogger/curielogger.log 20M
        command:
          - /bin/bash
          - -c
          - --
{{- end }}
        ports:
        - containerPort: 9514
          name: logger-rsyslog
        - containerPort: 9001
          name: logger-grpc
        - containerPort: 2112
          name: logger-p8s
        livenessProbe:
          tcpSocket:
            port: logger-grpc
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        resources:
          limits:
            memory: "500Mi"
            cpu: "900m"
          requests:
            memory: "20Mi"
            cpu: {{ .Values.global.requests.cpu.curielogger }}
        volumeMounts:
{{- if $curielogger.extraVolumeMounts }}
{{ toYaml $curielogger.extraVolumeMounts | indent 10 }}
{{- end }}
{{- if eq .Values.global.settings.curiefense_es_forwarder "filebeat" }}
          - name: curielogger
            mountPath: /var/log/curielogger
{{- end }}
      restartPolicy: Always
      imagePullSecrets:
        {{- .Values.global.imagePullSecrets | toYaml | nindent 8  }}
      serviceAccountName: ""
{{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
{{- end }}
      volumes:
{{- if $curielogger.extraVolumes }}
{{ toYaml $curielogger.extraVolumes | indent 6 }}
{{- end }}
{{- if eq .Values.global.settings.curiefense_es_forwarder "filebeat" }}
      - name: curielogger
        emptyDir: {}
      - name: filebeat-configmap
        configMap:
          name: filebeat-configmap
{{- end }}
